---
deployment:
  tasks:
    - source /home/io0rbcflm0qh/virtualenv/kirnaz/3.6/bin/activate && cd /home/io0rbcflm0qh/kirnaz
    - pip install -r requirements.txt
    - python manage.py collectstatic --no-input
    - python manage.py migrate
    - touch tmp/restart.txt