# Generated by Django 3.1.7 on 2021-06-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='num',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
