# Generated by Django 3.2 on 2021-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210815_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='msgto',
            field=models.BooleanField(),
        ),
    ]
