# Generated by Django 3.2 on 2021-08-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_msgto_conversation_msgtoadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='convofiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='convomedia')),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convofiles', to='chat.conversation')),
            ],
        ),
    ]
