# Generated by Django 3.2 on 2021-08-24 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_convofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='msgby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgby', related_query_name='convo', to='chat.user'),
        ),
    ]
