# Generated by Django 3.2 on 2021-08-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_conversation_msgby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convofiles',
            name='msg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convofiles', to='chat.conversation'),
        ),
    ]
