# Generated by Django 3.2 on 2021-08-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='anum',
            new_name='alternativePhone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='num',
            new_name='phone',
        ),
    ]
