# Generated by Django 3.2 on 2021-08-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210831_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alternativePhone',
            new_name='alternative_Phone',
        ),
    ]
