# Generated by Django 3.2.6 on 2022-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='readbyadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='readbyuser',
            field=models.BooleanField(default=False),
        ),
    ]
