# Generated by Django 3.2.6 on 2022-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20220219_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='lastseen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
