# Generated by Django 3.2.6 on 2022-02-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_status_lastseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='profile/default.png', upload_to='profile'),
        ),
    ]
