# Generated by Django 3.2.6 on 2022-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='convofiles',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
