# Generated by Django 3.2 on 2021-08-14 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0024_ourclients'),
        ('dashboard', '0002_delete_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='["Included in Our Packge","Procedure","document","Memorandum","Register","FAQS","Signification","Our Clients"]', max_length=1000)),
                ('reg_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
    ]
