# Generated by Django 3.2 on 2021-08-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sectionsothernavs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionsothernavs',
            name='reg_title',
        ),
        migrations.DeleteModel(
            name='Sections',
        ),
        migrations.DeleteModel(
            name='Sectionsothernavs',
        ),
    ]
