# Generated by Django 3.2 on 2021-08-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210815_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='section',
            field=models.CharField(default='["Top Form section","Included in Our Packge","Procedure,"Package icons","document","Memorandum","Register","FAQS","Signification","Our Clients"]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sectionsothernavs',
            name='section',
            field=models.CharField(default='["Top Form section","Included in Our Packge","Procedure,"Package icons","document","Memorandum","Register","FAQS","Signification","Our Clients"]', max_length=1000),
        ),
    ]
