# Generated by Django 3.2 on 2021-08-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_icon_iconver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='icon',
        ),
        migrations.DeleteModel(
            name='iconver',
        ),
    ]
