# Generated by Django 3.2.6 on 2022-02-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_makepaymentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('AdminTitle', models.CharField(max_length=30)),
                ('favicon', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.CreateModel(
            name='emailSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('tsl', models.BooleanField()),
                ('ssl', models.BooleanField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('activate', models.BooleanField(help_text='other mail is automatically disabled')),
            ],
        ),
    ]
