# Generated by Django 3.2 on 2021-08-10 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenu', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegistrationSubMenu', to='registration.registration')),
            ],
        ),
        migrations.CreateModel(
            name='SubRegistrationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=500)),
                ('tag_content', models.TextField(blank=True, null=True)),
                ('Optionalicon', models.FileField(blank=True, upload_to='img')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registration')),
            ],
        ),
    ]
