# Generated by Django 3.2 on 2021-08-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationsubmenu',
            name='slug',
        ),
    ]
