# Generated by Django 3.2 on 2021-08-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_subregistrationcontent_tag_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsubmenu',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegistrationSubMenu', to='registration.registration'),
        ),
    ]
