# Generated by Django 3.2 on 2021-08-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_registrationsubmenu_title'),
        ('registration', '0003_registrationsubmenu_slug'),
    ]

    operations = [
    ]
