# Generated by Django 3.2 on 2021-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20210810_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subregistrationcontent',
            name='heading1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subregistrationcontent',
            name='heading2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subregistrationcontent',
            name='heading3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
