# Generated by Django 3.2 on 2021-08-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210810_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subregistrationcontent',
            old_name='heading1ans',
            new_name='heading1_details',
        ),
        migrations.RenameField(
            model_name='subregistrationcontent',
            old_name='heading2ans',
            new_name='heading2_details',
        ),
        migrations.RenameField(
            model_name='subregistrationcontent',
            old_name='heading3ans',
            new_name='heading3_details',
        ),
    ]
