# Generated by Django 3.2 on 2021-08-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210810_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleSlideDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('heading1_details', models.TextField(blank=True, null=True)),
                ('heading2', models.CharField(blank=True, max_length=500, null=True)),
                ('heading2_details', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, upload_to='img')),
                ('image2', models.ImageField(blank=True, upload_to='img')),
                ('image3', models.ImageField(blank=True, upload_to='img')),
                ('image4', models.ImageField(blank=True, upload_to='img')),
                ('image5', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='TitleSlide',
        ),
        migrations.AlterField(
            model_name='subregistrationcontent',
            name='Optionalicon',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
