# Generated by Django 3.2 on 2021-08-10 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20210810_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutRegistraionSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('heading1_details', models.TextField(blank=True, null=True)),
                ('heading2', models.CharField(blank=True, max_length=500, null=True)),
                ('heading2_details', models.TextField(blank=True, null=True)),
                ('Optionalicon', models.ImageField(blank=True, upload_to='img')),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRegisterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('heading12', models.CharField(blank=True, max_length=500, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='PackageIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Sainification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='TitleSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TitleSlideDetails',
        ),
        migrations.RemoveField(
            model_name='subregistrationcontent',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='subregistrationcontent',
            name='heading1_details',
        ),
        migrations.RemoveField(
            model_name='subregistrationcontent',
            name='heading2',
        ),
        migrations.RemoveField(
            model_name='subregistrationcontent',
            name='heading2_details',
        ),
        migrations.RemoveField(
            model_name='subregistrationcontent',
            name='heading3',
        ),
        migrations.RemoveField(
            model_name='subregistrationcontent',
            name='heading3_details',
        ),
    ]
