# Generated by Django 3.2 on 2021-08-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20210810_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titleslide',
            name='title',
        ),
        migrations.AddField(
            model_name='titleslide',
            name='reg_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titleslide',
            name='title1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='titleslide',
            name='title2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='titleslide',
            name='title3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='titleslide',
            name='title4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='titleslide',
            name='title5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='titleslide',
            name='title6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='titleslide',
            name='title7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
