# Generated by Django 3.2 on 2021-08-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20210811_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titleslide',
            name='reg_title',
        ),
        migrations.RemoveField(
            model_name='titleslide',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='titleslide',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='titleslide',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='titleslide',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='titleslide',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='titleslide',
            name='title6',
        ),
        migrations.RemoveField(
            model_name='titleslide',
            name='title7',
        ),
        migrations.AddField(
            model_name='titleslide',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
