# Generated by Django 3.2 on 2021-08-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20210811_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyRegisterDetails',
            new_name='CompanyRegisterRequirements',
        ),
    ]
