# Generated by Django 3.2 on 2021-08-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_rename_companyregisterdetails_companyregisterrequirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyregisterrequirements',
            old_name='heading12',
            new_name='heading2',
        ),
    ]
