# Generated by Django 3.2 on 2021-08-11 11:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_rename_heading12_companyregisterrequirements_heading2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
