# Generated by Django 3.2 on 2021-08-12 06:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_auto_20210811_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequired',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
