# Generated by Django 3.2 on 2021-08-12 06:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_alter_documentrequired_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregisterrequirements',
            name='content1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyregisterrequirements',
            name='content2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
