# Generated by Django 3.2 on 2021-08-12 12:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_remove_sainification_content1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
