# Generated by Django 3.2 on 2021-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_memorandum_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
