# Generated by Django 3.2 on 2021-08-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0021_alter_procedure_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
