# Generated by Django 3.2 on 2021-08-14 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ImageField(upload_to='clients')),
                ('content', models.TextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
    ]
