# Generated by Django 3.2 on 2021-08-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_ourclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourclients',
            name='SignatureOptional',
            field=models.ImageField(blank=True, upload_to='clientsign'),
        ),
    ]
