# Generated by Django 3.2 on 2021-08-14 12:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_alter_registrationsubmenu_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subregistrationcontent',
            old_name='Optionalicon',
            new_name='BannerImg',
        ),
        migrations.RenameField(
            model_name='subregistrationcontent',
            old_name='tagline',
            new_name='formtitle',
        ),
        migrations.RenameField(
            model_name='subregistrationcontent',
            old_name='submenu',
            new_name='reg_title',
        ),
        migrations.AddField(
            model_name='subregistrationcontent',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subregistrationcontent',
            name='subtitle',
            field=models.CharField(default='title', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subregistrationcontent',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
