# Generated by Django 3.2 on 2021-08-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_alter_procedure_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='image',
            new_name='icon',
        ),
    ]
