# Generated by Django 3.2 on 2021-08-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_auto_20210818_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationsubmenu')),
            ],
        ),
    ]
