# Generated by Django 3.2 on 2021-08-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
