# Generated by Django 3.2 on 2021-08-27 12:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_contacts_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, upload_to='about')),
            ],
        ),
    ]
