# Generated by Django 3.2 on 2021-09-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_alter_aboutcontent_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationsubmenu',
            name='slug',
        ),
    ]
