# Generated by Django 3.2 on 2021-09-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_remove_registrationsubmenu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubmenu',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
