# Generated by Django 3.2 on 2021-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_registrationsubmenu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[(1, 'registration'), (2, 'othernavs')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
