# Generated by Django 3.2.6 on 2022-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0041_blognews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubmenu',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
    ]
