# Generated by Django 3.2.6 on 2022-02-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('registration', '0042_registrationsubmenu_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognews',
            name='reg_title',
        ),
        migrations.AddField(
            model_name='blognews',
            name='content_type',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blognews',
            name='object_id',
            field=models.PositiveIntegerField(default=53),
            preserve_default=False,
        ),
    ]
