# Generated by Django 3.2.6 on 2022-02-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0043_auto_20220202_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
    ]
