# Generated by Django 3.2.6 on 2022-02-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_registration_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='type',
            field=models.CharField(choices=[('1', 'registration'), ('2', 'othernavs')], max_length=1),
        ),
    ]
