# Generated by Django 3.2.6 on 2022-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_auto_20220203_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='pincode',
            field=models.CharField(max_length=500),
        ),
    ]
