# Generated by Django 3.2.6 on 2022-02-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0046_alter_contacts_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='pincode',
            new_name='message',
        ),
    ]
