# Generated by Django 3.2.6 on 2021-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_delete_ourservicesoffrings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServicesOffrings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
