# Generated by Django 3.2 on 2021-08-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_ourservicesoffrings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurServicesOffrings',
            new_name='Offrings',
        ),
    ]
