# Generated by Django 3.2 on 2021-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_ourservicesoffrings_offrings'),
    ]

    operations = [
        migrations.CreateModel(
            name='headbanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, max_length=500)),
                ('banner_content', models.CharField(blank=True, max_length=1500)),
                ('banneerimg', models.ImageField(blank=True, upload_to='banner')),
            ],
        ),
    ]
