# Generated by Django 3.2 on 2021-08-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('othernavs', '0006_rename_optionalicon_subregistrationcontent_bannerimg'),
        ('registration', '0028_auto_20210814_1803'),
        ('Home', '0006_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='page',
        ),
        migrations.AddField(
            model_name='links',
            name='orpage2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='othernavs.registrationsubmenu'),
        ),
        migrations.AddField(
            model_name='links',
            name='page1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.registrationsubmenu'),
        ),
    ]
