# Generated by Django 3.2 on 2021-08-16 09:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='imgaes')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
