# Generated by Django 3.2 on 2021-08-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='icon',
            field=models.FileField(upload_to='imgaes'),
        ),
    ]
