# Generated by Django 3.2 on 2021-08-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_addblog_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addblog',
            old_name='conntent',
            new_name='content',
        ),
    ]
