# Generated by Django 3.2 on 2021-08-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='ammount',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
