# Generated by Django 3.2 on 2021-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_orderplaced_ammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='other_data',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
