# Generated by Django 3.2 on 2021-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_orderplaced_other_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='ammount',
            field=models.FloatField(),
        ),
    ]
