# Generated by Django 3.2 on 2021-09-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20210901_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
