# Generated by Django 3.2 on 2021-09-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_alter_blognews_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='type',
            field=models.CharField(choices=[('1', 'News'), ('2', 'Blogs'), ('3', 'Article')], max_length=1),
        ),
    ]
