# Generated by Django 3.2.6 on 2021-12-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_makepaymentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0024_alter_blognews_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Payments')),
                ('ammount', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('other_data', models.CharField(default='nodata', max_length=1000)),
                ('payreq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.makepaymentrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
