# Generated by Django 3.2.6 on 2022-02-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_auto_20211213_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.TextField(max_length=100)),
                ('otherPhones', models.CharField(max_length=100)),
            ],
        ),
    ]
