# Generated by Django 3.2.6 on 2022-02-22 10:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_taggeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessquery',
            name='reply',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
