# Generated by Django 3.2 on 2021-08-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxfiling', '0002_remove_taxfiling_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxfiling',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
