# Generated by Django 3.2 on 2021-08-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxfiling', '0003_taxfiling_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxfiling',
            name='tag_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='tagline',
            field=models.CharField(default='', max_length=500),
        ),
    ]
