# Generated by Django 3.2 on 2021-08-14 09:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submenu', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RegistrationSubMenu', to='othernavs.registration')),
            ],
        ),
        migrations.CreateModel(
            name='TitleSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubRegistrationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(max_length=500)),
                ('Optionalicon', models.ImageField(blank=True, upload_to='img')),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Sainification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='PackageIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='ourclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Profile', models.ImageField(upload_to='clients')),
                ('SignatureOptional', models.ImageField(blank=True, upload_to='clientsign')),
                ('content', models.TextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRegisterRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('content1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('heading2', models.CharField(blank=True, max_length=500, null=True)),
                ('content2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
            ],
        ),
        migrations.CreateModel(
            name='AboutRegistraionSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading1', models.CharField(blank=True, max_length=500, null=True)),
                ('heading1_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('heading2', models.CharField(blank=True, max_length=500, null=True)),
                ('heading2_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Optionalicon', models.ImageField(blank=True, upload_to='img')),
                ('reg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othernavs.registrationsubmenu')),
            ],
        ),
    ]
