# Generated by Django 3.2 on 2021-08-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('othernavs', '0002_rename_submenu_subregistrationcontent_reg_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrationsubmenu',
            unique_together={('title', 'submenu')},
        ),
    ]
