# Generated by Django 3.2 on 2021-08-14 12:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othernavs', '0003_alter_registrationsubmenu_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subregistrationcontent',
            old_name='tagline',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='subregistrationcontent',
            name='Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subregistrationcontent',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
