# Generated by Django 3.2 on 2021-08-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('othernavs', '0005_subregistrationcontent_formtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subregistrationcontent',
            old_name='Optionalicon',
            new_name='BannerImg',
        ),
    ]
