# Generated by Django 3.2.6 on 2022-02-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othernavs', '0008_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubmenu',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
    ]
