# Generated by Django 3.2.6 on 2022-02-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othernavs', '0010_registration_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationsubmenu',
            name='info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
