# Generated by Django 3.2.6 on 2022-02-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othernavs', '0011_registrationsubmenu_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationsubmenu',
            name='info',
        ),
        migrations.AddField(
            model_name='registration',
            name='info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
