# Generated by Django 3.2.6 on 2022-02-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('othernavs', '0012_auto_20220203_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='pincode',
            field=models.CharField(max_length=500),
        ),
    ]
